blank_issues_enabled: false
contact_links:
  - name: I have a problem or idea for the application
    url: https://github.com/timmo001/system-bridge/issues
    about: Please use the main repository to create issues for the app.
  - name: I have a question or need support
    url: https://github.com/timmo001/system-bridge/discussions
    about: Please use the discussions area of the main repository for getting help or asking questions.
  - name: I have a an issue with the Home Assistant integration
    url: https://github.com/home-assistant/core/issues
    about: Please report any integration issues with Home Asssitant to the Core repository of Home Assistant.
